-- Superseded by 03_production_backend.sql.
-- This migration was an early enterprise-pivot prototype built against the retired companies/bids schema.
-- It is intentionally a no-op for new TradeGrid environments.
