-- Superseded by 03_production_backend.sql.
-- This migration was the review-stage bridge from the historical schema to authenticated tenancy.
-- It is intentionally a no-op for new TradeGrid environments.
